root: true

env:
  es2020: true
  node: true

extends:
  - 'semistandard'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

overrides:
  - files:
      - 'packages/midnight-smoker/bin/**/*'
    parserOptions:
      sourceType: 'module'
  - env:
      mocha: true
    files:
      - 'packages/*/test/**/*'
    rules:
      '@typescript-eslint/no-unused-vars': 'off'

parser: '@typescript-eslint/parser'

rules:
  '@typescript-eslint/no-explicit-any': 'off'
  'no-useless-constructor': 'off'
  'lines-between-class-members': 'off'
  'no-use-before-define': 'off'
