root: true
env:
  node: true
  es2020: true
extends:
  - semistandard
  - prettier
parserOptions:
  sourceType: script
ignorePatterns:
  - 'node_modules/**/*'
  - 'coverage/**/*'
  - 'dist/**/*'
overrides:
  - files:
      - test/**/*.spec.js
    env:
      mocha: true
