root: true

env:
  es2020: true
  node: true

extends:
  - 'semistandard'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'

ignorePatterns:
  - 'node_modules/**/*'
  - 'coverage/**/*'
  - 'dist/**/*'
  - '__snapshots__/**/*'

overrides:
  - files:
      - 'bin/**/*'
    parserOptions:
      sourceType: 'module'
  - env:
      mocha: true
    files:
      - 'test/**/*'
    rules:
      '@typescript-eslint/no-unused-vars': 'off'

parser: '@typescript-eslint/parser'

rules:
  '@typescript-eslint/no-explicit-any': 'off'
  'no-useless-constructor': 'off'
  'lines-between-class-members': 'off'
