exports['midnight-smoker CLI should show help text 1'] = {
  "stdout": "smoker <script> [scripts..]\n\nRun tests against a package as it would be published\n\nPositionals:\n  script                                                                [string]\n  scripts                                                               [string]\n\nBehavior:\n  -r, --require       Package identifier for extra dependency needed by smoke\n                      tests                                              [array]\n      --workspace     One or more npm workspaces to test                 [array]\n      --all           Test all workspaces                              [boolean]\n      --include-root  Include the workspace root; must provide '--all' [boolean]\n      --install-args  Extra arguments to pass to `npm install`           [array]\n      --dir           Working directory to use  [string] [default: new temp dir]\n      --force         Overwrite working directory if it exists         [boolean]\n      --clean         Truncate working directory; must provide '--force'\n                                                                       [boolean]\n      --npm           Path to `npm` executable [string] [default: `npm` in PATH]\n      --verbose       Print output from npm                            [boolean]\n      --bail          When running scripts, halt on first error        [boolean]\n      --json          Output JSON only                                 [boolean]\n\nOptions:\n      --version  Show version number                                   [boolean]\n      --help     Show help                                             [boolean]",
  "stderr": "",
  "exitCode": 0
}

exports['midnight-smoker CLI should smoke test this and produce JSON output 1'] = {
  "stdout": "{\n  \"results\": [\n    {\n      \"pkgName\": \"midnight-smoker\",\n      \"script\": \"smoke\",\n      \"rawResult\": {\n        \"command\": \"<path/to>/bin/npm run-script smoke\",\n        \"escapedCommand\": \"<path/to>/bin/npm\\\" run-script smoke\",\n        \"exitCode\": 0,\n        \"stdout\": \"\\n> midnight-smoker@<version> smoke\\n> <path/to/>smoker.js --version\\n\\n<version>\",\n        \"stderr\": \"\",\n        \"failed\": false,\n        \"timedOut\": false,\n        \"isCanceled\": false,\n        \"killed\": false\n      }\n    }\n  ],\n  \"total\": 1,\n  \"executed\": 1,\n  \"scripts\": [\n    \"smoke\"\n  ]\n}",
  "stderr": "",
  "exitCode": 0
}
